### PR TITLE
Added Language Utilities section

### PR DESCRIPTION
**Pull request by juandopazo**
Fixes issue #6.

I'm not sure this is a necessary addition. This functions are mostly internal utilities. Some I believe eventually become very useful to developers like Y.Lang.isValue() and $.each/Y.Array.each, but I'm not 100% sure adding them to the Rosetta Stone helps or just makes noise.

### CODE REVIEW

**Comment by rgrove** [comment]
Other than the inline comments I made, this looks good on the YUI side. I do think there's value in documenting these utilities since it's useful to understand how they work (and how they differ) in each library.

**Comment by juandopazo** [comment]
`jQuery.isPlainObject([]) === false`.

I actually thought `Y.Lang.isObject([])` returned false. I guess in practice one shouldn't check if something is a "plain object". It's best to just use the object as it is (check for the properties you need, etc). But shouldn't there be a way in YUI to do the same?

**Comment by rgrove** [comment]
Yeah, YUI does need an `isPlainObject` equivalent. Now that I own the Lang module, I guess I should add it!

**Comment by juandopazo** [comment]
Whenever I try to explain the difference with `isPlainObject` I can't really understand the logic behind `Y.Lang.isObject`. Shouldn't `Y.Lang.isObject([], true)` also return false? Why was the second parameter chosen to make it fail only for functions?

**Comment by rgrove** [comment]
`isObject()` takes the point of view that arrays are objects because, well, they really are, and also because `typeof [] === 'object'`.

In any case, I added `isPlainObject()` last night. It'll show up in the main yui3 repo soon; in the meantime, you can see it in my fork: https://github.com/rgrove/yui3/commit/d45403d8bf1ce1b4bcbdbae86a9a9c15130ae800

As soon as @paulirish signs off on your changes, we can merge 'em in!

**Comment by paulirish** [comment]
`type()` and `now()` were added in 1.4.3 and this commit says 1.4.2.. but other than that.. LGTM

**Comment by rgrove** [comment]
Should we bump the jQuery version number? We're actually quite a bit behind. Anyone have any interest in getting us current with 1.6.1?

**Comment by juandopazo** [comment]
I was thinking about that. jQuery's been pretty stable. I'll give it a look and see if anything changed.

**Comment by juandopazo** [comment]
I looked around and it seems that there are only two changes:
- jQuery added .prop() to access DOM properties instead of mapping to domNode.setAttribute. It is equivalent to using .get()/.set() in YUI
- YUI as of 3.4.0 has nodelist.filter()

**Comment by rgrove** [comment]
Dunno why I waited so long to merge this. Sorry about that.

If you want to open another pull request that updates jQuery and YUI to the latest versions, that'd be awesome.

**Pull request merged**
